filter:
    paths: [src/*]
checks:
    php: true
build:
    environment:
        postgresql: false
        redis: false
    nodes:
        lowest:
            environment:
                php: 7.2
            dependencies:
                override:
                    - composer update --prefer-lowest --no-interaction
                    - composer show
            tests:
                override:
                    - composer test
        current:
            environment:
                php: 7.4
            tests:
                override:
                    - composer check
                    - command: composer test-coverage
                      coverage:
                          file: 'tests/reports/coverage.xml'
                          format: 'clover'
                    - php-scrutinizer-run
