name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-verion: [7.3, 7.4, 8.0-rc]
    container: php:${{ matrix.php-verion }}

    steps:
      - name: Install packages
        run: apt-get update && apt-get install -y git unzip

      - name: Install composer
        run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - uses: actions/checkout@v2
      
      - name: Validate composer.json
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Run test suite
        run: composer run-script ci
