name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        additional-flags: [""]
        php-version: [7.3, 7.4]
        include:
          php-version: 7.3
          composer-flags: --prefer-lowest
    container: php:${{ matrix.php-version }}
    steps:
      - name: Install packages
        run: |
          apt-get update
          apt-get install -y git unzip

      - name: Install composer
        run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - uses: actions/checkout@v2
      
      - name: Validate composer.json
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer
          restore-keys: |
            ${{ runner.os }}-composer

      - name: Install dependencies
        run: |
          composer update ${{ matrix.additional-flags }} --no-progress --no-suggest
          composer show

      - name: Run test suite
        run: composer run-script ci
