name: PHP
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prefer: [ lowest, dist ]
        php-version: [ 7.3, 7.4 ]
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpunit

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php-verion }}-${{ matrix.prefer }}-composer

      - name: Install dependencies
        run: |
          composer validate
          composer update --prefer-${{ matrix.prefer }} --no-progress
          composer show

      - run: phpunit

      - uses: codecov/codecov-action@v1
        with:
          file: tests/reports/coverage.xml
          fail_ci_if_error: true
          verbose: true

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: vendor/
          key: ${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: composer update --no-progress

      - run: phpunit --coverage-clover=tests/reports/coverage.xml

      - uses: codecov/codecov-action@v1
        with:
          file: tests/reports/coverage.xml
          fail_ci_if_error: true
          verbose: true
